bitmakerla/estela

estela-api/api/views/job_data.py, estela-api/docs/api.yaml, estela-web/src/components/JobDataListPage/index.tsx, estela-web/src/services/api/generated-api/apis/ApiApi.ts
@Adriana618 Query that delete requests data from a job
=> BITMAKER-1792 Delete Request Data on Demand

.github/workflows/deploy-main-docs.yml, docs/_config.yml, docs/estela-cli/commands/context.md, docs/estela-cli/commands/create_cronjob.md, docs/estela-cli/commands/create_job.md, docs/estela-cli/commands/update_cronjob.md, docs/estela-cli/commands/update_job.md, docs/estela/api/credentials.md, docs/estela/installation/helm-variables.md, docs/estela/installation/main-guide.md, docs/estela/queueing.md, estela-api/README.md, estela-web/README.md, installation/README.md, queueing/README.md
Ticket: https://tasks.bitmaker.dev/issues/1867
=> BITMAKER-1867: Configure estela subdomain and gh actions

.github/pull_request_template.md
Ticket: https://tasks.bitmaker.dev/issues/1866
=> BITMAKER-1866: Define a PR template for Github contributions to estela

.github/workflows/deploy-main-docs.yml, docs/README.md, docs/assets/swagger-template.hbs, docs/estela/api/endpoints.html
_Fixing the docs workflow_.
* _https://tasks.bitmaker.dev/issues/1839_.
=> BITMAKER-1839: Fix workflow

estela-web/src/components/CronJobCreatePage/index.tsx, estela-web/src/components/CronJobDetailPage/index.tsx, estela-web/src/components/CronJobListPage/index.tsx, estela-web/src/components/JobCreatePage/index.tsx, estela-web/src/components/ProjectJobListPage/index.tsx, estela-web/src/components/SpiderDetailPage/index.tsx, estela-web/src/services/api/generated-api/apis/ApiApi.ts, estela-web/src/services/api/generated-api/models/DeleteJobData.ts, estela-web/src/services/api/generated-api/models/Deploy.ts, estela-web/src/services/api/generated-api/models/DeployCreate.ts, estela-web/src/services/api/generated-api/models/DeployUpdate.ts, estela-web/src/services/api/generated-api/models/GetLogs.ts, estela-web/src/services/api/generated-api/models/InlineResponse2005.ts, estela-web/src/services/api/generated-api/models/Permission.ts, estela-web/src/services/api/generated-api/models/Project.ts, estela-web/src/services/api/generated-api/models/ProjectJob.ts, estela-web/src/services/api/generated-api/models/ProjectUpdate.ts, estela-web/src/services/api/generated-api/models/Spider.ts, estela-web/src/services/api/generated-api/models/SpiderCronJob.ts, estela-web/src/services/api/generated-api/models/SpiderCronJobCreate.ts, estela-web/src/services/api/generated-api/models/SpiderCronJobUpdate.ts, estela-web/src/services/api/generated-api/models/SpiderJob.ts, estela-web/src/services/api/generated-api/models/SpiderJobArg.ts, estela-web/src/services/api/generated-api/models/SpiderJobCreate.ts, estela-web/src/services/api/generated-api/models/SpiderJobEnvVar.ts, estela-web/src/services/api/generated-api/models/SpiderJobTag.ts, estela-web/src/services/api/generated-api/models/SpiderJobUpdate.ts, estela-web/src/services/api/generated-api/models/Token.ts, estela-web/src/services/api/generated-api/models/UserDetail.ts
Updating current page variable in ProjectJobListPage to fix pagination.
* https://tasks.bitmaker.dev/issues/1926
=> BITMAKER-1926: Fix pagination in project jobs view

estela-web/README.md
=> Updating documentation link

.github/workflows/lint-mr-web.yml, estela-web/package.json, estela-web/postcss.config.js, estela-web/src/assets/index.css, estela-web/src/components/LoginPage/index.tsx, estela-web/src/index.tsx, estela-web/tailwind.config.js, estela-web/yarn.lock
estela Login front implementation and first setup
https://tasks.bitmaker.dev/issues/2054
=> BITMAKER-2054 Adding tailwind to the project

CODE_OF_CONDUCT.md
Help estela repo improve compared to the community standards.
https://tasks.bitmaker.dev/issues/1909
=> BITMAKER-1909 Create CODE_OF_CONDUCT.md

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md
Help estela repo improve compared to the community standards
https://tasks.bitmaker.dev/issues/1909
=> BITMAKER-1909 Update issue templates

CODE_OF_CONDUCT.md, CONTRIBUTING.md, README.md
Set Up Estela For Hacktoberfest Contributions
https://tasks.bitmaker.dev/issues/2060
=> BITMAKER-2060 Set Up Estela For Hacktoberfest Contributions

estela-api/config/settings/base.py, estela-api/config/settings/test.py, estela-api/engines/example_engine.py
_Removing unused variables and files_.
* _[Github Issue ID](https://tasks.bitmaker.dev/issues/1963)_.
=> BITMAKER-1963: Improve setting files

estela-web/src/components/ProjectMemberPage/index.tsx, estela-web/src/components/ProjectMemberPage/styles.scss, estela-web/src/routes/index.tsx
estela web: Implement "Members" component
https://tasks.bitmaker.dev/issues/2085
=> BITMAKER-2085 Adding Members component

estela-web/src/components/ProjectDetailPage/index.tsx, estela-web/src/components/ProjectMemberPage/index.tsx, estela-web/src/components/ProjectMemberPage/styles.scss, estela-web/src/shared/projectSidenav/index.tsx, estela-web/tailwind.config.js
estela-web: Implement "In Project/ Members" mockup
https://tasks.bitmaker.dev/issues/2081
=> BITMAKER-2081 estela-web: "In Project/ Members" mockup

estela-web/src/assets/icons/copy.svg, estela-web/src/components/DeployListPage/index.tsx, estela-web/src/components/DeployListPage/styles.scss, estela-web/src/components/ProjectMemberPage/index.tsx, estela-web/tailwind.config.js
estela-web Deploy design implementation
https://tasks.bitmaker.dev/issues/2069
=> BITMAKER-2069 estela-web Deploy design implementation

estela-web/src/assets/icons/add.svg, estela-web/src/components/ProjectDashboardPage/index.tsx, estela-web/src/components/ProjectListPage/index.tsx, estela-web/src/components/ProjectListPage/styles.scss, estela-web/src/components/ProjectMemberPage/index.tsx, estela-web/src/shared/header/index.tsx
estela-web "General Dashboard" Implementation
https://tasks.bitmaker.dev/issues/2070?issue_count=135&issue_position=17&next_issue_id=2069&prev_issue_id=2074
=> BITMAKER-2070 estela-web "General Dashboard" Implementation

estela-web/src/assets/scss/index.scss
Fixing  colors estela buttons
https://tasks.bitmaker.dev/issues/2070?issue_count=135&issue_position=17&next_issue_id=2069&prev_issue_id=2074
=> BITMAKER-2070 Fixing estela:web button

estela-web/src/components/ProjectCreatePage/index.tsx, estela-web/src/components/ProjectListPage/index.tsx, estela-web/src/components/ProjectSettingsPage/index.tsx, estela-web/src/components/ProjectSettingsPage/styles.scss, estela-web/src/routes/index.tsx, estela-web/src/shared/projectSidenav/index.tsx, estela-web/tailwind.config.js
Added Project Settings Page
https://tasks.bitmaker.dev/issues/2082
=> BITMAKER-2082 estela Project Settings page implementation

estela-web/src/components/ProjectListPage/index.tsx
Get Role in Project List request
https://tasks.bitmaker.dev/issues/2132
=> BITMAKER-2132 Get Role in Project List request

estela-web/webpack.config.js
=> BITMAKER 2210-1: Fix webpack output problem

estela-web/webpack.config.js
Solving problem about publicPath.
* [_Issue ID_](https://tasks.bitmaker.dev/issues/2210).
=> BITMAKER-2210-2: Add env variable to publicPath

estela-web/package.json, estela-web/src/components/ProjectDashboardPage/index.tsx, estela-web/src/components/ProjectDashboardPage/styles.scss, estela-web/src/components/SpiderDetailPage/index.tsx, estela-web/yarn.lock
estela-web: Connect Resources Consumption in Dashboard component
https://tasks.bitmaker.dev/issues/2209
=> BITMAKER-2209 estela-web: Connect Resources Consumption in Dashboard component

README.md
estela-cli project mention in README.md
=> estela-cli project mention

estela-web/src/components/JobDetailPage/index.tsx, estela-web/src/components/SpiderDetailPage/index.tsx, estela-web/tailwind.config.js
Implement "Jobs/Overview" mockup.
* https://tasks.bitmaker.dev/issues/2101.
=> Bitmaker 2101 estela-web: Implement "Jobs/Overview" mockup

estela-web/package.json, estela-web/src/components/CronJobDetailPage/index.tsx, estela-web/src/components/DeployListPage/index.tsx, estela-web/src/components/JobDetailPage/index.tsx, estela-web/src/components/NotificationsInboxPage/index.tsx, estela-web/src/components/NotificationsSettingsPage/index.tsx, estela-web/src/components/ProjectCronJobListPage/index.tsx, estela-web/src/components/ProjectDashboardPage/index.tsx, estela-web/src/components/ProjectJobListPage/index.tsx, estela-web/src/components/ProjectListPage/index.tsx, estela-web/src/components/ProjectMemberPage/index.tsx, estela-web/src/components/ProjectSettingsPage/index.tsx, estela-web/src/components/SettingsDataPersistencePage/index.tsx, estela-web/src/components/SettingsPasswordPage/index.tsx, estela-web/src/components/SettingsProfilePage/index.tsx, estela-web/src/components/SpiderDetailPage/index.tsx, estela-web/src/components/SpiderListPage/index.tsx, estela-web/src/services/auth.service.ts, estela-web/src/shared/header/index.tsx, estela-web/src/shared/notificationsList/index.tsx, estela-web/src/shared/notificationsSidenav/index.tsx, estela-web/src/shared/profileSettingsSidenav/index.tsx, estela-web/src/shared/projectSidenav/index.tsx, estela-web/src/shared/projectSidenav/styles.scss, estela-web/yarn.lock
Solve estela-web warnings & reformat components code
https://tasks.bitmaker.dev/issues/2162
=> BITMAKER-2162 Solve estela-web warnings & reformat components code

estela-web/src/assets/icons/doubleLeft.svg, estela-web/src/assets/icons/doubleRight.svg, estela-web/src/components/ProjectActivityPage/index.tsx, estela-web/src/components/ProjectActivityPage/styles.scss, estela-web/src/routes/index.tsx
Implement "In Projects/Activity" mockup
https://tasks.bitmaker.dev/issues/2102
=> BITMAKER-2102 estela-web: Implement "In Projects/Activity"

docs/estela/installation/helm-variables.md, docs/estela/installation/main-guide.md, estela-web/src/routes/index.tsx, installation/helm-chart/values.yaml.example
Fix estela-web routes and improve documentation.
=> Bitmaker-2237-2: Fix estela-web routes and improve documentation

docs/estela-cli/install.md
estela-cli: Add pip estela package to onboarding
https://tasks.bitmaker.dev/issues/2235
=> estela-cli: Add pip estela package to onboarding

estela-web/src/components/JobDetailPage/index.tsx
=> BITMAKER-2374: Fix problem

estela-web/webpack.mf.config.js
Create a checkout flow using stripe UI components.
https://tasks.bitmaker.dev/issues/2322
=> BITMAKER-2322: BC-billing-web: Create checkout flow with prebuilt UI stripe components.

estela-web/src/components/ProjectDashboardPage/index.tsx
estela-web: Issues with UsageRecord request
https://tasks.bitmaker.dev/issues/2274
=> BITMAKER-2274 estela-web: Issues with UsageRecord request

docs/estela/installation/helm-variables.md, installation/helm-chart/values.yaml.example
As part of @Jgaldos onboarding ticket, some minor fixes on documentation were added.
* BITMAKER-2214
=> BITMAKER-2214: add minor fixes on documentation.

estela-api/core/admin.py, estela-web/src/components/ProjectCronJobListPage/index.tsx, estela-web/src/components/ProjectJobListPage/index.tsx
estela-web: Implement Custom Add CreditCard Message
[* _Github Issue ID_.](https://tasks.bitmaker.dev/issues/2292)
=> BITMAKER-2292 estela-web: Implement Custom Add CreditCard Message

estela-api/api/serializers/project.py, estela-api/api/views/auth.py, estela-api/api/views/project.py, estela-api/config/settings/base.py, estela-api/docs/api.yaml, estela-web/src/app.tsx, estela-web/src/components/LoginPage/index.tsx, estela-web/src/components/NotificationsSettingsPage/index.tsx, estela-web/src/components/ProjectCronJobListPage/index.tsx, estela-web/src/components/ProjectDashboardPage/index.tsx, estela-web/src/components/ProjectJobListPage/index.tsx, estela-web/src/components/ProjectListPage/index.tsx, estela-web/src/context/UserContext.tsx, estela-web/src/context/UserProvider.tsx, estela-web/src/services/api/generated-api/models/ProjectUsage.ts, estela-web/src/services/auth.service.ts, estela-web/src/shared/header/index.tsx, estela-web/src/shared/notificationsList/index.tsx
. Some error were found in the production of estela:
- In ProjectDashboardPage page the copy project id button doesn’t work.
- Delete hard coded notifications or let know the user this feature isn’t implemented yet in production.
- When usage records aren’t registered, the spin in the dashboard spins indefinetly.
- On the shared/header component if no role is found for a user BMC shows null in the UI.
- External notification from microfrontend doesn’t show.
- Sometimes a google pay button appears in the modal for adding a card.
* https://tasks.bitmaker.dev/issues/2481.
=> BITMAKER-2481 estela-web: Fix issues on estela's frontend production version

estela-web/src/assets/scss/index.scss, estela-web/src/components/CronJobDetailPage/index.tsx, estela-web/src/components/DeployListPage/index.tsx, estela-web/src/components/ProjectCronJobListPage/index.tsx, estela-web/src/components/ProjectDashboardPage/index.tsx, estela-web/src/components/ProjectJobListPage/index.tsx, estela-web/src/components/SpiderDetailPage/index.tsx, estela-web/src/shared/index.tsx, estela-web/src/shared/paginationItem/index.tsx
estela reports some warnings when you go to the next page in some tables, In other cases, pagination doesn't work, its changes on the same page. Also, it needs to update styling according to FIgma mockups.
https://tasks.bitmaker.dev/issues/2325
=> BITMAKER-2325: estela-web Pagination issues

docs/estela-cli/quickstart.md, docs/estela/installation/helm-variables.md
Fix format in some parts of the documentation.
=> [MRG] Fix format in documentation.

estela-api/api/serializers/auth.py, estela-api/api/views/auth.py, estela-api/docs/api.yaml, estela-web/src/app.tsx, estela-web/src/components/LoginPage/index.tsx, estela-web/src/components/ProjectDashboardPage/index.tsx, estela-web/src/components/ProjectListPage/index.tsx, estela-web/src/context/UserContext.tsx, estela-web/src/context/UserProvider.tsx, estela-web/src/context/index.ts, estela-web/src/services/api/generated-api/models/Token.ts, estela-web/src/services/api/generated-api/models/UserDetail.ts, estela-web/src/services/auth.service.ts, estela-web/src/shared/header/index.tsx, estela-web/webpack.mf.config.js
Create a context that handles important user data and connect it with microfrontend part in estela.
* https://tasks.bitmaker.dev/issues/2536.
=> BITMAKER 2536 estela-web: Connect user context to microfrontend in estela

estela-web/src/assets/icons/trash.svg, estela-web/src/components/JobDetailPage/index.tsx, estela-web/src/shared/notifications/index.tsx
estela-web Add Delete button on scraped job data
[* _Github Issue ID_.](https://tasks.bitmaker.dev/issues/2508)
=> BITMAKER-2508 estela-web Add Delete button on scraped job data

estela-api/api/serializers/auth.py, estela-api/api/views/auth.py, estela-web/src/components/DeployListPage/index.tsx, estela-web/src/components/ProjectCronJobListPage/index.tsx, estela-web/src/components/ProjectDashboardPage/index.tsx, estela-web/src/components/ProjectJobListPage/index.tsx, estela-web/src/components/ProjectSettingsPage/index.tsx, estela-web/src/components/SpiderListPage/index.tsx, estela-web/src/shared/header/index.tsx
Some typos were reported on estela we need to fix this, and also make sure the text showed in the mockups (https://www.figma.com/file/Z7B9w9UuqvO6hp0plhyCid/Bitmaker----ESTELA?node-id=21%3A204&t=I4Bxzy0ylAVkS5VN-0) correspond to the text in the frontend, also some issues with buttons such as logout in microfrontend were found, we need to solve this issues.
Tasks:
- Solve issues with microfrontend and correct typos.
- Issues from this ticket are solved.
* https://tasks.bitmaker.dev/issues/2583.
=> BITMAKER-2583 estela-microfrontend: Fix issues with some components in microfrontend and correct typos in frontend

estela-api/api/permissions.py, estela-api/api/views/project.py
Add a Superuser role that works in the frontend
https://tasks.bitmaker.dev/issues/2627
=> BITMAKER-2627 Create a superuser role

estela-web/src/components/JobDetailPage/index.tsx
- Fix typo in job requests variable name
- Fix "storage" shown as "bandwidth" and vice-versa in the job detail page.
=> (Frontend) Fix typo in job requests variable name

estela-web/src/components/ProjectJobListPage/index.tsx, estela-web/src/components/SpiderDetailPage/index.tsx, estela-web/src/components/SpiderListPage/index.tsx
Fix SpiderList pagination and selection to run new job
[* _Github Issue ID_.](https://tasks.bitmaker.dev/issues/3020)
=> BITMAKER-3020 Fix pagination and spider selection

estela-web/src/components/ProjectJobListPage/index.tsx
Correct selected spider from spider detail page
[* _Github Issue ID_.](https://tasks.bitmaker.dev/issues/3027)
=> BITMAKER-3027 Correct selected spider from spider detail page

estela-api/api/views/job_data.py
We do not used the "paged" mode in either estela-web nor estela-cli. This is just some cleanup.
* https://tasks.bitmaker.dev/issues/3024
=> BITMAKER-3024: Remove unused "paginated" mode in data retrieval

estela-web/src/components/Stats/StatsTableSection.tsx, estela-web/src/pages/ProjectDashboardPage/index.tsx, estela-web/src/shared/spin/index.tsx, estela-web/src/shared/spin/styles.scss, estela-web/src/utils.ts
Temporal jobs traceability was replaced in the refactoring: https://github.com/bitmakerla/estela/pull/191.
Add traceability.
- Jobs traceability is recovered.
https://tasks.bitmaker.dev/issues/3339.
=> BITMAKER-3339

estela-web/src/components/Stats/StatsTableSection.tsx, estela-web/src/pages/ProjectDashboardPage/index.tsx
Reduce the table stats size.
- The table is shown well.
* https://tasks.bitmaker.dev/issues/3363.
=> BITMAKER-3363 Stats module: update table width of jobs data

estela-web/src/app.tsx, estela-web/src/defaultComponents/ExternalScripts/index.tsx
Setting environment to add google analytics
[* _Github Issue ID_.](https://tasks.bitmaker.dev/issues/2745)
=> BITMAKER-2745: Add ExternalScripts Component

estela-api/engines/kubernetes.py
Limit the pod privileges when run a job.
=> [MRG] Limit pod privileges.

docs/estela-cli/quickstart.md
=> [MRG] Add documentation for estela requests.

estela-api/core/cronjob.py
- Fix CrontabSchedule create and update operations
=> Fix CrontabSchedule create and update operations

estela-api/api/views/stats.py, estela-api/docs/api.yaml, estela-web/src/components/Stats/StatsTableSection.tsx, estela-web/src/pages/ProjectDashboardPage/index.tsx, estela-web/src/pages/SpiderDetailPage/index.tsx, estela-web/src/pages/SpiderListPage/index.tsx, estela-web/src/pages/SpiderListPage/styles.scss, estela-web/src/services/api/generated-api/apis/ApiApi.ts
Stats module frontend: spider stats
https://tasks.bitmaker.dev/issues/3542
=> SpiderStats module frontend

estela-web/src/pages/JobDataPage/index.tsx
I am attaching a screen recording of the glitch in the logs page. If you paginate enough through the logs of a spider, it is probable that you find the same glitch.
Completion criteria:
- Fix the glitch.
https://tasks.bitmaker.dev/issues/3723
=> BITMAKER-3723: estela-web. Fix logs list glitch

.github/pull_request_template.md, .github/workflows/deploy-main-docs.yml, .github/workflows/pr-preview-docs.yml, docs/_config.yml, docs/estela/web/routes.md, docs/estela/web/services.md, estela-api/README.md, estela-web/README.md, estela-web/src/pages/DeployListPage/index.tsx, installation/README.md, installation/helm-chart/values.yaml.example, queueing/README.md
_Change base url from docs/ to /_.
=> change[docs]: Change base url from docs/ to /

estela-web/src/components/ProxySettingsPage/ProxyForm.tsx
* Enable proxies in manual config.
=> [MRG] Enable proxies in manual config.

estela-api/docker-conf/Dockerfile-django-api
- (hotfix)Copy executables to the API Dockerfile final stage
=> (hotfix)Copy executables to the API Dockerfile final stage

estela-web/src/components/ProxySettingsPage/ProxyForm.tsx, installation/local/docker-compose.yaml
_Please include a summary of the changes, relevant motivation and context_.
=> change proxy password form type

database_adapters/db_adapters.py, estela-api/api/serializers/job.py, estela-api/api/utils.py, estela-api/api/views/job_data.py, estela-api/docker-conf/Dockerfile-celery-beat, estela-api/docker-conf/Dockerfile-celery-worker, estela-api/docker-conf/Dockerfile-django-api, estela-api/docs/api.yaml, estela-web/src/pages/JobDetailPage/index.tsx, estela-web/src/services/api/generated-api/models/SpiderJob.ts
_Please include a summary of the changes, relevant motivation and context_.
=> BITMAKER-5846: Add storage size

estela-api/api/views/project.py, estela-web/src/pages/JobDetailPage/index.tsx
Add item count in job overview and item job detail
=> [MRG] feat: Add itemcount in project job overview & item job detail

estela-api/core/models.py
It just increases the value max_length field of the env var model.
=> [MRG] Increase the value max_length env var.

estela-api/core/models.py
Fix value length of env var value.
=> [MRG] Fix value length of env var value.

estela-api/api/views/spider.py, estela-api/docs/api.yaml, estela-web/src/pages/CronjobCreateModal/index.tsx, estela-web/src/pages/JobCreateModal/index.tsx, estela-web/src/services/api/generated-api/apis/ApiApi.ts, estela-web/src/services/api/generated-api/models/Deploy.ts, estela-web/src/services/api/generated-api/models/Spider.ts, estela-web/src/shared/notifications/index.tsx
Add pre-loading state, search and lazy loading to Job Modals.
=> feat: Add pre-loading state, search and lazy loading to Job Modals.

estela-web/src/pages/JobCreateModal/index.tsx, estela-web/src/pages/JobDetailPage/index.tsx
_Please include a summary of the changes, relevant motivation and context_.
=> [MRG] Refactor job modal
