- docs/estela-cli/commands/context.md
- docs/estela-cli/commands/create_cronjob.md
- docs/estela-cli/commands/create_job.md
- docs/estela-cli/commands/update_cronjob.md
- docs/estela-cli/commands/update_job.md
There is not command that update DataStatus for jobs
Update Cronjob command doesn't allow data_expiry_days and data_status field, and it's required to create a job
estela CLI : https://github.com/bitmakerla/estela-cli/blob/master/estela_cli/
> BITMAKER-1862 Command line estela CLI to support UPDATE DataRetention fields

- .github/workflows/deploy-main-docs.yml
Hot fix: change the branch name of the gh workflow file
Ticket: https://tasks.bitmaker.dev/issues/1867
> BITMAKER-1867-fix: Change branch name

- README.md
We need to define the badges, links, description, and GitHub topics of estela repositories:
Consider all the github editable fields that offer a better understanding of the repositories
> BITMAKER-1840 estela: Configure repository descriptions

- database_adapters/db_adapters.py
- queueing/Dockerfile
- queueing/consumer.py
- queueing/inserter.py
- queueing/utils.py
_When the database fails while the Kafka consumers are inserting, the items that fail to be inserted are discarded and log the error inserting. This means we lose data, which cannot happen. Modify the consumer not to delete items that fail to be inserted_.
* _https://tasks.bitmaker.dev/issues/1931_.
> BITMAKER-1931: Handle items that fail to be inserted to the DB

- estela-web/src/components/JobDataListPage/index.tsx
"Delete data" does not return a notification until all data is deleted. This should say "we are deleting your data" and have a "are you sure?" modal.
Clicking "Delete data" does not ask for confirmation, which is dangerous. Also, the "data deleted" notification arrives after all data has been deleted. We should replace this with a "Deleting data..." notification.
https://tasks.bitmaker.dev/issues/1927
> BITMAKER-1927 Improve "Delete data" in frontend

- queueing/consumer.py
- queueing/inserter.py
- queueing/utils.py
_Fix the memory leak caused by kafka consumers_.
* _https://tasks.bitmaker.dev/issues/2118_.
> BITMAKER-2118: Fix high memory usage of Kafka consumers

- estela-api/api/views/project.py
When a request is made to estela usage endpoint (https://estela.bitmaker.la/docs/estela/api/endpoints.html#tag/api/operation/api_projects_usage) query parameters start_date and end_date are not handled in Project/View.
* https://tasks.bitmaker.dev/issues/2277.
> BITMAKER-2277 estela-api: Query parameters are not received on Usage endpoint in estela api

- docs/estela/installation/helm-variables.md
- estela-api/config/settings/base.py
- estela-api/config/urls.py
- installation/helm-chart/templates/API/api-secrets.yaml
- installation/helm-chart/values.yaml.example
Modify estela to use features that require keys, urls,  etc, in Django external apps.
* [_ID_](https://tasks.bitmaker.dev/issues/2324).
> BITMAKER-2324: Add urls and keys from django external apps

- estela-api/api/views/stats.py
- estela-api/core/tasks.py
- estela-web/src/components/JobDetailPage/index.tsx
- estela-web/src/components/ProjectDashboardPage/index.tsx
Some problems appeared in the revision of the UI mockups.
- Coverage bug
- Set full width of the chart.
- Test the backend for large periods of time queries.
* https://tasks.bitmaker.dev/issues/3121.
> BITMAKER-3121 global stats frontend: hot fix in charts section

- estela-web/src/pages/CronjobCreateModal/index.tsx
- estela-web/src/pages/JobCreateModal/index.tsx
- estela-web/src/pages/JobDetailPage/index.tsx
- estela-web/src/pages/ProjectDashboardPage/index.tsx
- estela-web/src/pages/ProjectJobListPage/index.tsx
- estela-web/src/pages/SettingsPasswordPage/index.tsx
- estela-web/src/pages/SpiderDetailPage/index.tsx
- estela-web/src/utils.ts
Issue on the processing time in the project dashboard, when entering an amount of seconds greater than one day it parses it wrong. E.g. in the attached image processing time in seconds are 121992.813125 this should be 33:53:12, but in frontend is 9:53:12.
Task:
* Fix the issue.
* The time format is correct.
* https://tasks.bitmaker.dev/issues/3270.
> BITMAKER-3270 Hot Fix global stats: Fix hours format

- estela-web/src/pages/JobDataPage/index.tsx
When manually entering the page we want for requests or logs, it also sets the page size to that value. So, when entering `page: 3`, it was also setting `pageSize: 3`, and we would only get 3 results of the specified page.
> Fix data pagination for requests and logs

- estela-api/api/serializers/stats.py
- estela-api/api/views/stats.py
- estela-api/docs/api.yaml
- estela-web/src/components/Stats/ChartsModalSection.tsx
- estela-web/src/components/Stats/ChartsSection.tsx
- estela-web/src/components/Stats/ProjectHealth.tsx
- estela-web/src/components/Stats/StatsDateModalContent.tsx
- estela-web/src/components/Stats/StatsTableSection.tsx
- estela-web/src/pages/JobDetailPage/index.tsx
- estela-web/src/pages/ProjectDashboardPage/index.tsx
- estela-web/src/services/api/generated-api/apis/ApiApi.ts
- estela-web/src/utils.ts
Some issues appeared in bitmaker cloud staging during black-box testing, see the [thread discussion](https://bitmakerla.slack.com/archives/C04TQNZE97Y/p1689971355166469):
- Query issues some details show more spiders than there are in the project.
- Change delay time to format HH:MM:SS.
- Processing time appear as NaN sometimes, instead it should be 0.
- Some jobs are not considered in the date detail.
Tasks:
- Solve the issues and testing.
- Deploy on staging and see results.
- Issues are solved..
* https://tasks.bitmaker.dev/issues/3570.
> BITMAKER-3570 Stats module: Fix issues on stats date modal

- estela-web/src/components/Stats/StatsDateModalContent.tsx
- estela-web/src/pages/JobDetailPage/index.tsx
- estela-web/src/utils.ts
Our current method of parsing the duration data received from the backend is incorrect. The durations are provided in the following format: "HH:MM:SS.SSSSSS". Here are a couple of examples:
"00:00:10.729321"
"00:01:13.422526"
In this format, the first example represents a duration of 10.729321 seconds.
Previously, we erroneously interpreted the last six digits (for instance, 729321 in the first example) as milliseconds. This interpretation is not accurate as these six digits represent fractional seconds and not milliseconds. We need to adjust our parsing to reflect this understanding.
> BITMAKER-3629 : Fix duration parsing.

- estela-web/src/pages/ProjectListPage/index.tsx
If we are an admin and we go the project list, we will appear as Admin for all projects and the text is capitalized instead of all in caps.
https://tasks.bitmaker.dev/issues/3721
> BITMAKER-3721: estela-web. Fix text casing when viewing stuff as admin

- estela-web/src/pages/CronJobDetailPage/index.tsx
- estela-web/src/pages/JobDetailPage/index.tsx
Completion criteria:
- Fix arguments overflowing in the details of jobs and cronjobs.
- Ensure that this doesn't happen for environment variables or tags either.
- Fix the spider name overflowing. We could show only up to X characters and then have a "show more" as we do for logs.
https://tasks.bitmaker.dev/issues/3722
> BITMAKER-3722: Fix details overflow in the job and cronjob detail sections

- estela-api/api/views/auth.py
- estela-api/config/settings/base.py
We should not allow multiple confirmations of an email registration.
We probably need to verify if the user email is already verified here: https://github.com/bitmakerla/estela/blob/1a1789ffdf6d2e82bf3b297b5786f6cc58090567/estela-api/api/views/auth.py#L94.
Completion criteria:
- Users should only be able to confirm their emails once after registration. Check if their email is already validated before sending more registration confirmation emails.
https://tasks.bitmaker.dev/issues/2953
> BITMAKER-2953: Invalidate registration confirmation token after activation

- estela-web/.env.development.example
- estela-web/src/constants.ts
- estela-web/src/pages/LoginPage/index.tsx
- estela-web/src/routes/index.tsx
We can activate or deactivate the frontend Register views based on an environment variable.
* [https://tasks.bitmaker.dev/issues/3858](https://tasks.bitmaker.dev/issues/3858)
> [change]estela-web: Show register page based on the REGISTER_PAGE_ENABLED variable

- estela-web/src/pages/ProjectJobListPage/index.tsx
In the Jobs overview section of Estela, add a new column displaying the number of items, JOB OVERVIEW
https://tasks.bitmaker.dev/issues/5759
> BITMAKER-5759: Add numbers of items

- estela-api/api/serializers/auth.py
- estela-api/api/serializers/project.py
- estela-api/api/views/project.py
- estela-api/docs/api.yaml
- estela-web/src/pages/ProjectMemberPage/index.tsx
- estela-web/src/services/api/generated-api/models/ProjectUpdate.ts
- estela-web/src/services/api/generated-api/models/UserProfile.ts
- queueing/Dockerfile
SuperAdmins should be able to change what user owns a project. When making this change, the previous owner should be set as an ADMIN because no project should have more than 1 owner.
Completion criteria:
- Allow superadmins to change the owner of a project.
https://tasks.bitmaker.dev/issues/3750
> feat: Allow superadmins to transfer project ownership

- .github/workflows/trigger-dev-deployment.yml
- Added trigger-dev-deployment.yml workflow
- Triggers bitmaker-cloud-deploy when pushing to dev branch
- Sends repository dispatch with commit info and metadata
- Enables automatic deployment to development environment
> feat: add auto-deployment trigger for dev branch
